---
- name: Check current CPU usage
  hosts: all
  tasks:

    - name: Get current CPU usage percentage
      ansible.builtin.shell: |
        set -o pipefail
        top -bn1 | grep "Cpu(s)" | awk '{print 100 - $8 "%"}'
      register: cpu_usage
      changed_when: false

    - name: Show CPU usage
      ansible.builtin.debug:
        msg: "Current CPU usage is {{ cpu_usage.stdout }}"
