---
- name : pull and run docker image on dynamic server
  hosts : all
  tasks :

    - name : Ensure docker
      package : 
        name : docker
        state : present

    - name : Start docker service
      service : 
        name : docker
        state : started 
        enabled : true
    
    - name : copy shell script to target
      copy : 
        src : /home/dsidam/run_app.sh
        dest : /home/dsidam/images/run_app.sh
        mode : '0755'
    
    - name : execute the shell script
      shell : /home/dsidam/images/run_app.sh