---
- name: Pull and run docker image on dynamic server
  hosts: all
  tasks:

    - name: Ensure docker
      ansible.builtin.package:
        name: docker
        state: present

    - name: Start docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Copy shell script to target
      ansible.builtin.copy:
        src: /home/dsidam/run_app.sh
        dest: /home/dsidam/images/run_app.sh
        mode: '0755'

    - name: Execute the shell script
      ansible.builtin.command: /home/dsidam/images/run_app.sh
      changed_when: true
