name: Ansible CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run ansible-lint
        uses: ansible/ansible-lint@v25.5.0
        with:
          args: ""
          setup_python: true
          working_directory: "."
          requirements_file: "requirements.yml"
          expected_return_code: 0
          gh_action_ref: "v25.5.0"
